# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  default:
    desc: list all tasks
    cmds:
      - task --list
    silent: true

  inspect:
    desc: Run MCP Inspector against the local server
    env:
      WORKING_DIRECTORY: "{{.HOME}}/Repos/CSharp/dynamodb-efcore-provider"
    cmds:
      - dotnet build -c Release
      - npx -y @modelcontextprotocol/inspector dotnet run --project src/DotnetTest.Mcp -c Release
